[package]
name = "quinn-h3"
version = "0.0.1"
authors = [
    "Benjamin Saunders <ben.e.saunders@gmail.com>", "Dirkjan Ochtman <dirkjan@ochtman.nl>",
    "Jean-Christophe BEGUE <begue.jc@gmail.com>"
]
license = "MIT/Apache-2.0"
repository = "https://github.com/djc/quinn"
description = "QUIC HTTP/3 protocol implementation"
readme = "../README.md"
keywords = ["quic", "http3", "qpack"]
categories = [ "network-programming", "asynchronous" ]
workspace = ".."
edition = "2018"

[package.metadata.docs.rs]
all-features = true

[badges]
codecov = { repository = "djc/quinn" }
maintenance = { status = "experimental" }
travis-ci = { repository = "djc/quinn" }

[dependencies]
quinn-proto = { path = "../quinn-proto", version = "0.3.0" }
quinn = { path = "../quinn", version = "0.3.0" }
bytes = "0.4.7"
bitlab = "0.8.1"
lazy_static = "1"
err-derive = "0.1.5"

[dev-dependencies]
proptest = "0.9.1"
assert_matches = "1.1"

###### Example

failure = "0.1"
slog-term = "2"
structopt = "0.2.7"
tokio = "0.1.6"
tokio-io = "0.1"
tokio-current-thread = "0.1"
tokio-reactor = "0.1.1"
url = "1.7"
rcgen = "0.2"
directories = "1.0.2"
rand = "0.6.5"
crc = "1.8.1"
unwrap = "1.2.1"
# slog = { version = "2.1", features = ["max_level_trace", "release_max_level_warn"] }
slog = "2.1"
futures = "0.1.21"
err-derive = "0.1.5"

[[example]]
name = "h3"
